# Generated by Django 5.2.15 on 2026-06-17 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_documentassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL', 'Llamada'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Nota'), ('PROMISE', 'Promesa'), ('PAYMENT_INFO', 'Información de pago')], max_length=30)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_actions', to='portfolio.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_actions', to='portfolio.document')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de cobranza',
                'verbose_name_plural': 'Acciones de cobranza',
                'ordering': ['-action_date', '-created_at'],
            },
        ),
    ]
