# Generated by Django 5.2.15 on 2026-06-17 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('portfolio', '0002_documentassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise_date', models.DateField()),
                ('promised_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Vigente'), ('EXPIRED', 'Vencida'), ('FULFILLED', 'Cumplida'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_promises_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_promises', to='portfolio.customer')),
            ],
            options={
                'verbose_name': 'Promesa de pago',
                'verbose_name_plural': 'Promesas de pago',
                'ordering': ['promise_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromiseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promise_documents', to='portfolio.document')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promise_documents', to='management.paymentpromise')),
            ],
            options={
                'verbose_name': 'Documento asociado a promesa',
                'verbose_name_plural': 'Documentos asociados a promesas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['customer'], name='management__custome_ddf85b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['promise_date'], name='management__promise_7277cb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['status'], name='management__status_84d89e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['payment_confirmed'], name='management__payment_3632f3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentpromise',
            index=models.Index(fields=['created_by'], name='management__created_e89687_idx'),
        ),
        migrations.AddIndex(
            model_name='promisedocument',
            index=models.Index(fields=['promise'], name='management__promise_816e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='promisedocument',
            index=models.Index(fields=['document'], name='management__documen_2794c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='promisedocument',
            constraint=models.UniqueConstraint(fields=('promise', 'document'), name='unique_promise_document'),
        ),
    ]
