# Generated by Django 5.2.15 on 2026-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_paymentpromise_promisedocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('evaluation_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de prioridad',
                'verbose_name_plural': 'Reglas de prioridad',
                'ordering': ['evaluation_order', 'code'],
            },
        ),
    ]
