# Generated by Django 5.2.15 on 2026-06-19 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_seed_priority_rules'),
        ('portfolio', '0004_seed_official_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PROMISE_EXPIRED', 'Promesa vencida'), ('PROMISE_DUE_TODAY', 'Promesa vence hoy'), ('NO_MANAGEMENT_7_DAYS', 'Sin gestión 7 días'), ('HIGH_PRIORITY_DOCUMENT', 'Documento alta prioridad'), ('UNASSIGNED_DOCUMENT', 'Documento sin asignar'), ('CRITICAL_CUSTOMER', 'Cliente crítico'), ('PAYMENT_RECEIVED', 'Pago recibido'), ('PROMISE_FULFILLED', 'Promesa cumplida')], max_length=40)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítica'), ('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja'), ('INFO', 'Informativa')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'Nueva'), ('VIEWED', 'Vista'), ('IN_PROGRESS', 'En gestión'), ('RESOLVED', 'Resuelta'), ('POSTPONED', 'Pospuesta'), ('DISMISSED', 'Descartada')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_alerts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_alerts', to='portfolio.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_alerts', to='portfolio.document')),
                ('promise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_alerts', to='management.paymentpromise')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='management__alert_t_82b54c_idx'), models.Index(fields=['severity', 'status'], name='management__severit_33761e_idx'), models.Index(fields=['created_at'], name='management__created_c88c77_idx'), models.Index(fields=['due_at'], name='management__due_at_48fb5c_idx')],
            },
        ),
    ]
