# Generated by Django 5.2.15 on 2026-06-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_operationalalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_type',
            field=models.CharField(choices=[('CALL', 'Llamada'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('NOTE', 'Nota'), ('PROMISE', 'Promesa'), ('PAYMENT_INFO', 'Información de pago'), ('ALERT_RESOLVED', 'Alerta resuelta'), ('ALERT_POSTPONED', 'Alerta pospuesta'), ('ALERT_REOPENED', 'Alerta reabierta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='operationalalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nueva'), ('VIEWED', 'Vista'), ('IN_PROGRESS', 'En gestión'), ('RESOLVED', 'Resuelta'), ('POSTPONED', 'Pospuesta'), ('DISMISSED', 'Descartada'), ('REOPENED', 'Reabierta')], default='NEW', max_length=20),
        ),
    ]
