# Generated by Django 5.2.15 on 2026-06-30 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_collectionaction_action_type_and_more'),
        ('portfolio', '0005_customercontact_do_not_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['status', '-created_at'], name='management__status_a67a77_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['status', 'due_at'], name='management__status_9fac0b_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['assigned_to', 'status', '-created_at'], name='management__assigne_703d41_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['document', 'status'], name='management__documen_67f31e_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalalert',
            index=models.Index(fields=['promise', 'status'], name='management__promise_44ba6a_idx'),
        ),
    ]
