# Generated by Django 5.2.15 on 2026-07-19 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('management', '0007_operationalalert_management__status_a67a77_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=700, unique=True)),
                ('mime_type', models.CharField(max_length=150)),
                ('extension', models.CharField(max_length=20)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_attachments', to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto operacional',
                'verbose_name_plural': 'Adjuntos operacionales',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mgmt_attach_target_idx'), models.Index(fields=['created_at'], name='mgmt_attach_created_idx'), models.Index(fields=['uploaded_by'], name='mgmt_attach_user_idx')],
            },
        ),
    ]
