# Generated by Django 5.2.15 on 2026-09-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_operationalattachment'),
        ('portfolio', '0010_alter_customerstatement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisedocument',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_customer_external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_doc_entry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='promisedocument',
            name='source_trans_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promisedocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_documents', to='portfolio.document'),
        ),
        migrations.AddIndex(
            model_name='promisedocument',
            index=models.Index(fields=['source', 'source_trans_id'], name='promise_source_trans_idx'),
        ),
        migrations.AddIndex(
            model_name='promisedocument',
            index=models.Index(fields=['source', 'source_customer_external_id', 'source_trans_id'], name='promise_ext_identity_idx'),
        ),
    ]
