# Generated by Django 5.2.15 on 2026-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_promisedocument_source_and_more'),
        ('portfolio', '0010_alter_customerstatement_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promisedocument',
            name='unique_promise_document',
        ),
        migrations.AddConstraint(
            model_name='promisedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('promise', 'document'), name='unique_promise_document'),
        ),
    ]
