# Generated by Django 5.2.15 on 2026-06-16 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login exitoso"),
                            ("LOGIN_FAILED", "Login fallido"),
                            ("LOGOUT", "Logout"),
                            ("SESSION_EXPIRED", "Sesión expirada"),
                            ("TOKEN_EXPIRED", "Token expirado"),
                            ("IDENTITY_ERROR", "Error de identidad"),
                            ("USER_DISABLED", "Usuario deshabilitado"),
                            ("ACCESS_DENIED", "Acceso denegado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "username_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Usuario informado al momento del evento.",
                        max_length=150,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-created_at"],
            },
        ),
    ]
