# Generated by Django 5.2.15 on 2026-06-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cluster', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['rut'], name='portfolio_c_rut_5a48a4_idx'), models.Index(fields=['external_id'], name='portfolio_c_externa_cbd8c6_idx'), models.Index(fields=['name'], name='portfolio_c_name_4d9e94_idx'), models.Index(fields=['cluster'], name='portfolio_c_cluster_50d1bb_idx'), models.Index(fields=['is_active'], name='portfolio_c_is_acti_5323f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de documento',
                'verbose_name_plural': 'Estados de documento',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='portfolio_d_name_cd10a9_idx'), models.Index(fields=['is_active'], name='portfolio_d_is_acti_6d8892_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subestado de documento',
                'verbose_name_plural': 'Subestados de documento',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='portfolio_d_name_b6bb5b_idx'), models.Index(fields=['is_active'], name='portfolio_d_is_acti_7270c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de documento',
                'verbose_name_plural': 'Etiquetas de documento',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='portfolio_d_name_95ded2_idx'), models.Index(fields=['is_active'], name='portfolio_d_is_acti_0e94d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portfolio.customer')),
            ],
            options={
                'verbose_name': 'Contacto de cliente',
                'verbose_name_plural': 'Contactos de cliente',
                'ordering': ['customer__name', '-is_primary', 'name'],
                'indexes': [models.Index(fields=['customer'], name='portfolio_c_custome_bf6e13_idx'), models.Index(fields=['email'], name='portfolio_c_email_0dec02_idx'), models.Index(fields=['is_primary'], name='portfolio_c_is_prim_c4f7eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('credit_note', 'Nota de crédito'), ('debit_note', 'Nota de débito'), ('other', 'Otro')], default='invoice', max_length=30)),
                ('document_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('external_source', models.CharField(choices=[('manual', 'Manual'), ('Fact_Vta_Reg', 'Fact_Vta_Reg'), ('NC_Vta_Reg', 'NC_Vta_Reg'), ('Pago_Vta_Reg', 'Pago_Vta_Reg')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portfolio.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='portfolio.documentstatus')),
                ('sub_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='portfolio.documentsubstatus')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='portfolio.documenttag')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['due_date', 'customer__name', 'document_number'],
                'indexes': [models.Index(fields=['customer'], name='portfolio_d_custome_4aa115_idx'), models.Index(fields=['trans_id'], name='portfolio_d_trans_i_bd847a_idx'), models.Index(fields=['document_type'], name='portfolio_d_documen_8a7eda_idx'), models.Index(fields=['document_number'], name='portfolio_d_documen_b08f08_idx'), models.Index(fields=['issue_date'], name='portfolio_d_issue_d_3fbcdf_idx'), models.Index(fields=['due_date'], name='portfolio_d_due_dat_1edf0d_idx'), models.Index(fields=['status'], name='portfolio_d_status__d12fdf_idx'), models.Index(fields=['sub_status'], name='portfolio_d_sub_sta_742ca6_idx'), models.Index(fields=['external_source'], name='portfolio_d_externa_ef8f8e_idx'), models.Index(fields=['balance_amount'], name='portfolio_d_balance_b10c9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('external_source', 'trans_id'), name='unique_document_by_source_trans_id'), models.UniqueConstraint(fields=('customer', 'document_type', 'document_number'), name='unique_document_by_customer_type_number')],
            },
        ),
    ]
