# Generated by Django 5.2.15 on 2026-06-17 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('initial', 'Asignación inicial'), ('reassignment', 'Reasignación'), ('balancing', 'Balanceo de carga'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portfolio.document')),
            ],
            options={
                'verbose_name': 'Asignación de documento',
                'verbose_name_plural': 'Asignaciones de documentos',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['document'], name='portfolio_d_documen_2ec3cc_idx'), models.Index(fields=['assigned_to'], name='portfolio_d_assigne_317a71_idx'), models.Index(fields=['assigned_by'], name='portfolio_d_assigne_9ff69f_idx'), models.Index(fields=['assignment_type'], name='portfolio_d_assignm_61d611_idx'), models.Index(fields=['assigned_at'], name='portfolio_d_assigne_cfc27c_idx'), models.Index(fields=['is_active'], name='portfolio_d_is_acti_958d86_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document',), name='unique_active_assignment_per_document')],
            },
        ),
    ]
