# Generated by Django 5.2.15 on 2026-06-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_documentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_reference', models.CharField(blank=True, max_length=120)),
                ('external_payment_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('source_table', models.CharField(blank=True, default='Pago_Vta_Reg', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portfolio.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portfolio.document')),
            ],
            options={
                'verbose_name': 'Pago aplicado',
                'verbose_name_plural': 'Pagos aplicados',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['document'], name='portfolio_p_documen_967be9_idx'), models.Index(fields=['customer'], name='portfolio_p_custome_632a16_idx'), models.Index(fields=['payment_date'], name='portfolio_p_payment_8847c8_idx'), models.Index(fields=['external_payment_id'], name='portfolio_p_externa_0babc5_idx')],
            },
        ),
    ]
