# Generated by Django 5.2.15 on 2026-06-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_seed_official_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='do_not_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='send_frequency',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='document_subtype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='document',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_refactored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='market_place',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='seller_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='source_base_folio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='source_doc_entry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='source_snapshot_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreditNoteApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_trans_id', models.CharField(max_length=100)),
                ('credit_document_number', models.CharField(max_length=100)),
                ('source_base_folio', models.CharField(blank=True, max_length=100)),
                ('credit_doc_entry', models.CharField(blank=True, max_length=100)),
                ('target_invoice_number', models.CharField(max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('credit_type', models.CharField(blank=True, max_length=50)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('source_snapshot_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_applications', to='portfolio.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_applications', to='portfolio.document')),
            ],
            options={
                'verbose_name': 'Aplicación de nota de crédito',
                'verbose_name_plural': 'Aplicaciones de notas de crédito',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['customer'], name='portfolio_c_custome_1b77cd_idx'), models.Index(fields=['document'], name='portfolio_c_documen_1cc0d9_idx'), models.Index(fields=['credit_trans_id'], name='portfolio_c_credit__c9e80a_idx'), models.Index(fields=['credit_document_number'], name='portfolio_c_credit__d08996_idx'), models.Index(fields=['target_invoice_number'], name='portfolio_c_target__a7ea87_idx'), models.Index(fields=['status'], name='portfolio_c_status_13bf54_idx'), models.Index(fields=['issue_date'], name='portfolio_c_issue_d_a93c72_idx')],
                'constraints': [models.UniqueConstraint(fields=('credit_trans_id', 'document'), name='unique_credit_note_application_by_trans_id_document')],
            },
        ),
    ]
