# Generated by Django 5.2.15 on 2026-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_customercontact_do_not_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='overpayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
