# Generated by Django 5.2.15 on 2026-07-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_document_overpayment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSupport',
            fields=[
                ('id', models.BigIntegerField(db_column='Id_Pk', primary_key=True, serialize=False)),
                ('document_number', models.IntegerField(blank=True, db_column='doc_num', null=True)),
                ('url', models.TextField(blank=True, db_column='url', null=True)),
                ('onedrive_item_id', models.CharField(blank=True, db_column='onedrive_item_id', max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_column='eliminado', default=False)),
            ],
            options={
                'verbose_name': 'Respaldo documental',
                'verbose_name_plural': 'Respaldos documentales',
                'db_table': 'Fact_scan_url2',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
