# Generated by Django 5.2.15 on 2026-08-26 17:08

import django.db.models.deletion
from django.db import migrations, models


def create_manual_reconciliation_substatus(apps, schema_editor):
    DocumentSubStatus = apps.get_model(
        "portfolio",
        "DocumentSubStatus",
    )

    DocumentSubStatus.objects.get_or_create(
        name="Cubierto por reconciliación manual",
        defaults={
            "is_active": True,
            "sort_order": 85,
        },
    )


def remove_manual_reconciliation_substatus(apps, schema_editor):
    DocumentSubStatus = apps.get_model(
        "portfolio",
        "DocumentSubStatus",
    )

    DocumentSubStatus.objects.filter(
        name="Cubierto por reconciliación manual",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_documentsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReconciliationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('source_rut', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('timeline_order_at', models.DateTimeField(blank=True, null=True)),
                ('source_table', models.CharField(default='Pago_Reconciliacion_Manual', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reconciliations', to='portfolio.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reconciliations', to='portfolio.document')),
            ],
            options={
                'verbose_name': 'Aplicación de reconciliación manual',
                'verbose_name_plural': 'Aplicaciones de reconciliación manual',
                'ordering': ['-timeline_order_at', '-created_at'],
                'indexes': [models.Index(fields=['document'], name='portfolio_m_documen_ea2bb0_idx'), models.Index(fields=['customer'], name='portfolio_m_custome_15e7fe_idx'), models.Index(fields=['source_id'], name='portfolio_m_source__6c624c_idx'), models.Index(fields=['invoice_number'], name='portfolio_m_invoice_f4b540_idx'), models.Index(fields=['timeline_order_at'], name='portfolio_m_timelin_49e16a_idx')],
            },
        ),

        migrations.RunPython(
            create_manual_reconciliation_substatus,
            remove_manual_reconciliation_substatus,
        ),
    ]
