# Generated by Django 5.2.15 on 2026-08-31 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_manualreconciliationapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('to_emails', models.JSONField(default=list)),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PREVIEW', 'Vista previa'), ('SENT', 'Enviado'), ('FAILED', 'Error de envío'), ('INVALIDATED', 'Invalidado')], default='PREVIEW', max_length=20)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('due_today_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('upcoming_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='microsoft_graph', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('pdf_filename', models.CharField(blank=True, max_length=255)),
                ('xlsx_filename', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_statements_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_statements', to='portfolio.customer')),
            ],
            options={
                'verbose_name': 'Estado de cuenta',
                'verbose_name_plural': 'Estados de cuenta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='portfolio_c_custome_e9cc04_idx'), models.Index(fields=['status', '-created_at'], name='portfolio_c_status_3d1cac_idx'), models.Index(fields=['created_by', '-created_at'], name='portfolio_c_created_fc5dab_idx'), models.Index(fields=['sent_at'], name='portfolio_c_sent_at_ea886c_idx')],
            },
        ),
    ]
