# Generated by Django 5.2.15 on 2026-08-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_customerstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatement',
            name='status',
            field=models.CharField(choices=[('PREVIEW', 'Vista previa'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('FAILED', 'Error de envío'), ('INVALIDATED', 'Invalidado')], default='PREVIEW', max_length=20),
        ),
    ]
