# Generated by Django 5.2.15 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_customerstatement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='work_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
