# Generated by Django 5.2.15 on 2026-09-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_document_purchase_order_document_work_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSAPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_name', models.CharField(blank=True, max_length=255)),
                ('account_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('sales_order_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('delivery_note_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True)),
                ('account_status', models.CharField(blank=True, max_length=20)),
                ('sap_status', models.CharField(blank=True, max_length=10)),
                ('inactive_comment', models.CharField(blank=True, max_length=200)),
                ('billing_emails_raw', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('portfolio_seller_name', models.CharField(blank=True, max_length=100)),
                ('portfolio_seller_email', models.CharField(blank=True, max_length=200)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sap_profile', to='portfolio.customer')),
            ],
            options={
                'verbose_name': 'Perfil SAP de cliente',
                'verbose_name_plural': 'Perfiles SAP de clientes',
                'indexes': [models.Index(fields=['account_status'], name='portfolio_c_account_324d2e_idx'), models.Index(fields=['sap_status'], name='portfolio_c_sap_sta_a141fd_idx'), models.Index(fields=['source_updated_at'], name='portfolio_c_source__758aef_idx')],
            },
        ),
    ]
