# Generated by Django 5.2.15 on 2026-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_customersapprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersapprofile',
            name='billing_emails_sap_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Última confirmación directa de U_Email_FV obtenida desde SAP Service Layer.', null=True),
        ),
        migrations.AddField(
            model_name='customersapprofile',
            name='phone_sap_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Última confirmación directa de Phone1 obtenida desde SAP Service Layer.', null=True),
        ),
    ]
