# apps/portfolio/constants.py

DOCUMENT_STATUS_UNASSIGNED = "Sin asignar"
DOCUMENT_STATUS_ASSIGNED = "Asignada"
DOCUMENT_STATUS_IN_PROGRESS = "En gestión"
DOCUMENT_STATUS_PAYMENT_SCHEDULED = "Pago programado"
DOCUMENT_STATUS_PAID = "Pagada"
DOCUMENT_STATUS_CLOSED = "Cerrada"

OFFICIAL_DOCUMENT_STATUSES = [
    DOCUMENT_STATUS_UNASSIGNED,
    DOCUMENT_STATUS_ASSIGNED,
    DOCUMENT_STATUS_IN_PROGRESS,
    DOCUMENT_STATUS_PAYMENT_SCHEDULED,
    DOCUMENT_STATUS_PAID,
    DOCUMENT_STATUS_CLOSED,
]


DOCUMENT_SUBSTATUS_CONTACTED = "Contactado"
DOCUMENT_SUBSTATUS_NO_CONTACT = "Sin contacto"
DOCUMENT_SUBSTATUS_REQUIRES_FOLLOW_UP = "Requiere seguimiento"
DOCUMENT_SUBSTATUS_PROMISE_PENDING_DATE = "Promesa pendiente de fecha"
DOCUMENT_SUBSTATUS_ACTIVE_PROMISE = "Promesa vigente"
DOCUMENT_SUBSTATUS_EXPIRED_PROMISE = "Promesa vencida"
DOCUMENT_SUBSTATUS_PARTIAL_PAYMENT_REPORTED = "Pago parcial informado"
DOCUMENT_SUBSTATUS_FULL_PAYMENT_REPORTED = "Pago total informado"

OFFICIAL_DOCUMENT_SUBSTATUSES = [
    DOCUMENT_SUBSTATUS_CONTACTED,
    DOCUMENT_SUBSTATUS_NO_CONTACT,
    DOCUMENT_SUBSTATUS_REQUIRES_FOLLOW_UP,
    DOCUMENT_SUBSTATUS_PROMISE_PENDING_DATE,
    DOCUMENT_SUBSTATUS_ACTIVE_PROMISE,
    DOCUMENT_SUBSTATUS_EXPIRED_PROMISE,
    DOCUMENT_SUBSTATUS_PARTIAL_PAYMENT_REPORTED,
    DOCUMENT_SUBSTATUS_FULL_PAYMENT_REPORTED,
]


DOCUMENT_TAG_CLAIMED = "Reclamada"
DOCUMENT_TAG_REINVOICING = "Refacturación"
DOCUMENT_TAG_CRITICAL_CUSTOMER = "Cliente crítico"
DOCUMENT_TAG_MARKETPLACE = "Marketplace"
DOCUMENT_TAG_DO_NOT_SEND = "No enviar"
DOCUMENT_TAG_REQUIRES_SUPERVISOR = "Requiere supervisor"
DOCUMENT_TAG_PAYMENT_PENDING_APPLICATION = "Pago pendiente de aplicar"
DOCUMENT_TAG_EXPIRED_PROMISE = "Promesa vencida"

OFFICIAL_DOCUMENT_TAGS = [
    DOCUMENT_TAG_CLAIMED,
    DOCUMENT_TAG_REINVOICING,
    DOCUMENT_TAG_CRITICAL_CUSTOMER,
    DOCUMENT_TAG_MARKETPLACE,
    DOCUMENT_TAG_DO_NOT_SEND,
    DOCUMENT_TAG_REQUIRES_SUPERVISOR,
    DOCUMENT_TAG_PAYMENT_PENDING_APPLICATION,
    DOCUMENT_TAG_EXPIRED_PROMISE,
]